In [1]:
# Student grades predicted based on absence - Eaaa, Autumn 2021
# Sila, 23rd August 2021.

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
col_names = ["Student_absence", "grade"]

In [4]:
df = pd.read_csv('StudentAbsenceGrade.csv')

In [5]:
df[['student_absence','grade']] = df['student_absence;grade'].str.split(';', expand=True)

In [6]:
print ( df .describe( include = 'all' ))

       student_absence;grade student_absence grade
count                    156             156   156
unique                    54              30     6
top                     31;7              23     7
freq                      14              24    58


In [7]:
# Remove empty cells

In [8]:
df.isnull().sum()

student_absence;grade    0
student_absence          0
grade                    0
dtype: int64

In [9]:
print(df)

    student_absence;grade student_absence grade
0                    0;10               0    10
1                    27;7              27     7
2                     0;7               0     7
3                    0;10               0    10
4                    65;0              65     0
..                    ...             ...   ...
151                  23;7              23     7
152                  62;2              62     2
153                  38;7              38     7
154                  54;0              54     0
155                  8;12               8    12

[156 rows x 3 columns]


In [10]:
print(df)

    student_absence;grade student_absence grade
0                    0;10               0    10
1                    27;7              27     7
2                     0;7               0     7
3                    0;10               0    10
4                    65;0              65     0
..                    ...             ...   ...
151                  23;7              23     7
152                  62;2              62     2
153                  38;7              38     7
154                  54;0              54     0
155                  8;12               8    12

[156 rows x 3 columns]


In [11]:
X = df[ "student_absence" ]
y = df[ "grade" ]

In [12]:
#Option 1 - Reshaping to (-1,1)
X = np.array(X).reshape(-1,1)

In [13]:
print(y)

0      10
1       7
2       7
3      10
4       0
       ..
151     7
152     2
153     7
154     0
155    12
Name: grade, Length: 156, dtype: object


In [14]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=51 )
print ("Shape of X_train = ", X_train.shape)
print ("Shape of y_train = ", y_train.shape)
print ("Shape of X_test = ", X_test.shape)
print ("Shape of y_test = ", y_test.shape)

Shape of X_train =  (124, 1)
Shape of y_train =  (124,)
Shape of X_test =  (32, 1)
Shape of y_test =  (32,)


In [15]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(solver='lbfgs',
                    alpha=1e-5,
                    hidden_layer_sizes=(8,),
                    random_state=1)

mlp.fit(X_train, y_train)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(8,), random_state=1,
              solver='lbfgs')

In [16]:
from sklearn.metrics import classification_report,confusion_matrix

In [17]:
#predictions
predictions = mlp.predict(X_test)

matrix = confusion_matrix(y_test,predictions)
print (matrix)
print (classification_report(y_test,predictions))

[[ 0  0  0  0  0  4]
 [ 0  0  3  0  0  4]
 [ 0  0  2  0  0  1]
 [ 0  0  0  0  0  2]
 [ 0  0  0  0  0  1]
 [ 0  0  0  0  0 15]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
          10       0.00      0.00      0.00         7
          12       0.40      0.67      0.50         3
           2       0.00      0.00      0.00         2
           4       0.00      0.00      0.00         1
           7       0.56      1.00      0.71        15

    accuracy                           0.53        32
   macro avg       0.16      0.28      0.20        32
weighted avg       0.30      0.53      0.38        32



C:\Users\sila\PycharmProjects\ML_Week11\venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sila\PycharmProjects\ML_Week11\venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\sila\PycharmProjects\ML_Week11\venv\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(resu